name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  # Allow to trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          update-environment: true

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install align-anything
        run: |
          python -m pip install -vvv --editable '.[lint]'

      - name: pre-commit
        run: |
          python -m pre-commit run --all-files

